---
title: "Comparison Tables"
author: "Gleb Furman"
date: "November 3, 2015"
output: html_document
---

```{r, cache = F, echo = F, warning = F, results = "hide", message = F}
library(plyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(moments)
library(tidyr)
library(htmlTable)

rm(list = ls())

results <- read.csv("20150929.csv")

results <- select(results, n, B, Estruct, Edist, HC:p10)
levels(results$B) <- c("Model 2", "Model 1")
results$test <- factor(results$test, levels = c("naive", "edgeKC", "saddle_V1", "saddle_V2", "Satt"))

levels(results$test) <- c("N", "E", "S_M", "S_E", "S")
levels(results$HC) <- c("0", "1", "2", "3", "4", "4m", "5")

compare <- function(y, x, max = .01427, target = .01) {
  vals <- cbind(y, x)
  
  vals[x == y] <- "equal"
  
  vals[(x > max & y <= max) | 
         (x > max & y > max & x > y) | 
         (x <= max & y <= max & 
            abs(target - x) > abs(target - y))] <- "y"
  
  vals[(x <= max & y > max) |
         (x > max & y > max & x < y) |
         (x <= max & y <= max & 
            abs(target - x) < abs(target - y))] <- "x"
 
  return(vals[,1])
}

```

#Size_25_p05
```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}
PIR <- filter(results, criterion == "size", n == "25") %>%
  mutate(method = paste(test, HC, sep = "_")) %>%
  select(n:Edist, coef, method, p05)

PIR <- merge(PIR, spread(PIR, key = method, value = p05))



PIR[,8:42] <- sapply(select(PIR, E_0:S_M_5), compare, x = PIR$p05)


gather(PIR, key = "vs", value = "winPercent", E_0:S_M_5) %>%
  group_by(method, vs) %>%
  summarize(winPercent = round(mean(winPercent == "x")*100, 2)) %>%
  spread(key = vs, value = winPercent) -> Size_25_p05

write.csv(Size_25_p05, file = "Size_25_p05.csv")

```

#Size_500_p05
```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}
PIR <- filter(results, criterion == "size", n == "500") %>%
  mutate(method = paste(test, HC, sep = "_")) %>%
  select(n:Edist, coef, method, p05)

PIR <- merge(PIR, spread(PIR, key = method, value = p05))



PIR[,8:42] <- sapply(select(PIR, E_0:S_M_5), compare, x = PIR$p05)


gather(PIR, key = "vs", value = "winPercent", E_0:S_M_5) %>%
  group_by(method, vs) %>%
  summarize(winPercent = round(mean(winPercent == "x")*100, 2)) %>%
  spread(key = vs, value = winPercent) -> Size_500_p05

write.csv(Size_500_p05, file = "Size_500_p05.csv")

```

#Size_25_p01
```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}
PIR <- filter(results, criterion == "size", n == "25") %>%
  mutate(method = paste(test, HC, sep = "_")) %>%
  select(n:Edist, coef, method, p01)

PIR <- merge(PIR, spread(PIR, key = method, value = p01))



PIR[,8:42] <- sapply(select(PIR, E_0:S_M_5), compare, x = PIR$p01)


gather(PIR, key = "vs", value = "winPercent", E_0:S_M_5) %>%
  group_by(method, vs) %>%
  summarize(winPercent = round(mean(winPercent == "x")*100, 2)) %>%
  spread(key = vs, value = winPercent) -> Size_25_p01

write.csv(Size_25_p01, file = "Size_25_p01.csv")

```

#Size_25_p05
```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, criterion == "size", n == 500) %>%
  select(n, Estruct, Edist, HC, coef, test, p05) %>%
  group_by(test, HC) %>%
  mutate(alpha = ifelse(quantile(p05, prob = .75) <= .05427,.5,.4)) %>%
  ggplot(aes(y = p05,
             x = test,
             fill = test,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(n ~ HC) +
  coord_cartesian(ylim = c(.000, .07)) + 
  geom_hline(aes(yintercept = .05427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .05)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of Sandwich Estimators with Adjustment",
       y = "Size",
       x = "Adjustments")
```

#Size_25_p01
```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, criterion == "size", n == 25) %>%
  select(n, Estruct, Edist, HC, coef, test, p01) %>%
  group_by(test, HC) %>%
  mutate(alpha = ifelse(quantile(p01, prob = .75) <= .01427,.5,.4)) %>%
  ggplot(aes(y = p01,
             x = test,
             fill = test,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(n ~ HC) +
  coord_cartesian(ylim = c(.000, .02)) + 
  geom_hline(aes(yintercept = .01427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .01)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of Sandwich Estimators with Adjustment",
       y = "Size",
       x = "Adjustments")
```