---
title: "HetRobust Analysis"
author: "Gleb Furman"
date: "October 8, 2015"
output: html_document
---

```{r, cache = F, echo = F, warning = F, results = "hide", message = F}
library(plyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(moments)
library(tidyr)

rm(list = ls())

results <- read.csv("20150929.csv")

results <- select(results, n, B, Estruct, Edist, HC:p10)
levels(results$B) <- c("Model 2", "Model 1")
results$test <- factor(results$test, levels = c("naive", "edgeKC", "saddle_V1", "saddle_V2", "Satt"))


```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, criterion == "size") %>%
  select(n, Estruct, Edist, HC, coef, test, p05) %>%
  group_by(test, HC, n) %>%
  mutate(alpha = ifelse(quantile(p05, prob = .75) <= .05427,.5,.4)) %>%
  ggplot(aes(y = p05,
             x = test,
             fill = test,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(n ~ HC) +
  coord_cartesian(ylim = c(.000, .075)) + 
  geom_hline(aes(yintercept = .05427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .05)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of Sandwich Estimators with Adjustment",
       y = "Size",
       x = "Adjustments")
```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, criterion == "size", n == 25) %>%
  select(Estruct, Edist, HC, coef, test, p05) %>%
  group_by(test, HC, Estruct) %>%
  mutate(alpha = ifelse(quantile(p05, prob = .75) <= .05427,.5,.4)) %>%
  ggplot(aes(y = p05,
             x = test,
             fill = test,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(Estruct ~ HC) +
  coord_cartesian(ylim = c(.000, .075)) + 
  geom_hline(aes(yintercept = .05427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .05)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of Sandwich Estimators with Adjustment at n = 25
       ",
       y = "Size",
       x = "Adjustments")
```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15, eval = F}
edm <- function() {
  
  # Distributions used in generating data
  b1 <- runif(10000, 0, 1)
  b2 <- rnorm(10000, 0, 1)
  b3 <- rchisq(10000, 1)
  b4 <- rnorm(10000, 0, 1)
  b5 <- runif(10000, 0, 1)
  
  # Four independant variables based on distributions
  x0 <- 1
  x1 <- 1 + b1
  x2 <- 3 * b1 + .6 * b2
  x3 <- 2 * b1 + .6 * b3
  x4 <- .1 * x1 + .9 * x3 - .8 * b4 + 4 * b5
  x2[x2 < -2.5] <- -2.5
  x4[x4 < -2.5] <- -2.5
  
  # One dummy variable created by splitting x2
  xD <- ifelse(x2 > 1.6, 1, 0)
  
  # Three types of homoscedastistic error distributions:
  
  En = rnorm(10000, 0, 1)
  Ech = (rchisq(10000, 5) - 5) / sqrt(10)
  Et = rt(10000, 5)

  # Seven types of error structures
  
  E0 = 1
  E1 = sqrt(x1)
  E2 = sqrt(x3 + 1.6)
  E3 = sqrt(x3) * sqrt(x4 + 2.5)
  E4 = sqrt(x1) * sqrt(x2 + 2.5) * sqrt(x3)
  E5 = ifelse(xD == 1, 1.5, 1)
  E6 = ifelse(xD == 1, 4, 1)
  
  X <- cbind(x0, x1, x2, x3, x4, xD)
  
  B = c(1, 1, 1, 1, 0, 0)
  
  Y <- as.vector(X %*% B)
  
  ESs <- cbind(E0, E1, E2, E3, E4, E5, E6)
  
  EnES <- data.frame(dist = "En", Y = Y, En * ESs)
  EchES <- data.frame(dist = "Ech", Y = Y, Ech * ESs)
  EtES <- data.frame(dist = "Et", Y = Y, Et * ESs)

  EDESs <- rbind(En = EnES, Ech = EchES, Et = EtES)
  


 
  return(EDESs)
}

EDists <-  edm()

backup <- EDists
EDists <- backup

EDists <-  melt(EDists, id.vars = c("dist", "Y"), variable.name = "EStructs", value.name = "x")
EDists <-  rbind(EDists, mutate(EDists, dist = "All"))

group_by(EDists, dist, EStructs) %>%
  summarize(stats = paste(round(mean(x)), 
                  round(sd(x),2), 
                  round(skewness(x),2), 
                  round(kurtosis(x),2), 
                  sep = "\n")) ->
  EDistStats

ggplot(EDists, aes(x = Y,
                   y = x)) +
  geom_point(alpha = .1,
             size = 1) +
  coord_cartesian(ylim = c(-30, 30)) +
  facet_grid(EStructs ~ dist) +
  geom_text(data = EDistStats, 
            aes(x = 15, 
                y = 1, 
                label = stats, 
                size = 5), 
            parse = F) +
  theme(legend.position = "none")

ggplot(EDists, aes(x = x,
                   y = ..density..)) +
  geom_histogram(binwidth = .1) +
  coord_cartesian(xlim = c(-10, 10)) +
  facet_grid(EStructs ~ dist) +
  geom_text(data = EDistStats, 
            aes(x = 5, 
                y = .3, 
                label = stats, 
                size = 5), 
            parse = F) +
  theme(legend.position = "none")



```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, test == "naive", criterion == "size") %>%
  select(n, Estruct, Edist, HC, coef, p05) %>%
  group_by(HC, Estruct, n) %>%
  mutate(alpha = ifelse(quantile(p05, prob = .75) <= .05427,.5,.4)) %>%
  ggplot(aes(x = HC,
             y = p05,
             fill = HC,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(n ~ Estruct) +
  geom_hline(aes(yintercept = .05427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .05)) +
  coord_cartesian(ylim = c(.000, .075)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of Naive Sandwich Estimators by Error Structure",
       y = "Size",
       x = "Sandwich Estimators")

```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, test == "edgeKC", criterion == "size") %>%
  select(n, Estruct, Edist, HC, coef, p05) %>%
  group_by(HC, Estruct, n) %>%
  mutate(alpha = ifelse(quantile(p05, prob = .75) <= .05427,.5,.4)) %>%
  ggplot(aes(x = HC,
             y = p05,
             fill = HC,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(n ~ Estruct) +
  geom_hline(aes(yintercept = .05427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .05)) +
  coord_cartesian(ylim = c(.000, .075)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of EdgeKC Sandwich Estimators by Error Structure",
       y = "Size",
       x = "Sandwich Estimators")

```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, test == "saddle_V1", criterion == "size") %>%
  select(n, Estruct, Edist, HC, coef, p05) %>%
  group_by(HC, Estruct, n) %>%
  mutate(alpha = ifelse(quantile(p05, prob = .75) <= .05427,.5,.4)) %>%
  ggplot(aes(x = HC,
             y = p05,
             fill = HC,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(n ~ Estruct) +
  geom_hline(aes(yintercept = .05427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .05)) +
  coord_cartesian(ylim = c(.000, .075)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of Model-Based Saddlepoint Sandwich Estimators by Error Structure",
       y = "Size",
       x = "Sandwich Estimators")

```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, test == "saddle_V2", criterion == "size") %>%
  select(n, Estruct, Edist, HC, coef, p05) %>%
  group_by(HC, Estruct, n) %>%
  mutate(alpha = ifelse(quantile(p05, prob = .75) <= .05427,.5,.4)) %>%
  ggplot(aes(x = HC,
             y = p05,
             fill = HC,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(n ~ Estruct) +
  geom_hline(aes(yintercept = .05427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .05)) +
  coord_cartesian(ylim = c(.000, .075)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of Empirical-Based Saddlepoint Sandwich Estimators by Error Structure",
       y = "Size",
       x = "Sandwich Estimators")

```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}

filter(results, test == "Satt", criterion == "size") %>%
  select(n, Estruct, Edist, HC, coef, p05) %>%
  group_by(HC, Estruct, n) %>%
  mutate(alpha = ifelse(quantile(p05, prob = .75) <= .05427,.5,.4)) %>%
  ggplot(aes(x = HC,
             y = p05,
             fill = HC,
             alpha = alpha)) +
  geom_boxplot() +
  facet_grid(n ~ Estruct) +
  geom_hline(aes(yintercept = .05427), linetype = "dashed") + 
  geom_hline(aes(yintercept = .05)) +
  coord_cartesian(ylim = c(.000, .075)) +
  theme_bw() + theme(legend.position = "bottom") + 
  scale_alpha(guide = 'none') +
  labs(title = "Performance of Satterthwaite Sandwich Estimators by Error Structure",
       y = "Size",
       x = "Sandwich Estimators")

```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}
HC3 <- filter(results, HC == "HC3", criterion == "size", test == "naive") %>%
  select(n:Edist, coef, naive = p05)

compare <- function(vals, nom = .05427) {
  if(vals[1] > nom & vals[2] <= nom) return("y")
  if(vals[1] <= nom & vals[2] > nom) return("x")
  if(vals[1] > nom & vals[2] > nom & vals[1] > vals[2]) return("y")
  if(vals[1] > nom & vals[2] > nom & vals[1] < vals[2]) return("x")
  if(vals[1] <= nom & vals[2] <= nom & vals[1] > vals[2]) return("x")
  if(vals[1] <= nom & vals[2] <= nom & vals[1] < vals[2]) return("y")
  return("equal")
}


filter(results, criterion == "size") %>%
  merge(HC3) %>%
  mutate(comp = unlist(apply(cbind(x = naive, y = p05), 1, compare))) ->
  H2HHC3

group_by(H2HHC3, HC, test) %>%
  summarize(percs = paste(round(mean(comp == "x"),2), round(mean(comp == "y"),2), sep = "\n")) -> 
  perc

ggplot(H2HHC3, aes(x = naive,
             y = p05,
             color = comp)) +
    geom_point(size = 1) +
    geom_abline(intercept = 0, slope = 1) + 
    geom_hline(aes(yintercept = .05)) + 
    geom_vline(aes(xintercept = .05)) +
    geom_hline(aes(yintercept = .05427), linetype = "dashed")+
    geom_vline(aes(xintercept = .05427), linetype = "dashed") +
    facet_grid(HC ~ test, scales = "free_y") +
  labs(title = "All Models vs Naive HC3",
       y = "HC1",
       x = "HC3") +
  geom_text(data = perc, 
            aes(x = .07, 
                y = .15, 
                label = percs, 
                size = 5,
                color = NA), 
            parse = F)




filter(H2HHC3, HC == "HC1", criterion == "size") %>%
  ggplot(aes(x = naive,
             y = p05,
             color = comp)) +
    geom_point(size = 1) +
    geom_abline(intercept = 0, slope = 1) + 
    geom_hline(aes(yintercept = .05)) + 
    geom_vline(aes(xintercept = .05)) +
    geom_hline(aes(yintercept = .05427), linetype = "dashed")+
    geom_vline(aes(xintercept = .05427), linetype = "dashed") +
    facet_wrap(~test) +
  labs(title = "Adjusted HC3 vs Naive HC3",
       y = "Adjusted HC3",
       x = "HC3")


filter(H2HHC3, HC == "HC1", criterion == "size") %>%
  ggplot(aes(x = naive,
             y = p05,
             color = comp)) +
    geom_point(size = 1) +
    geom_abline(intercept = 0, slope = 1) + 
    geom_hline(aes(yintercept = .05)) + 
    geom_vline(aes(xintercept = .05)) +
    geom_hline(aes(yintercept = .05427), linetype = "dashed")+
    geom_vline(aes(xintercept = .05427), linetype = "dashed") +
    facet_wrap(~test) +
  labs(title = "HC1 vs Naive HC3",
       y = "HC1",
       x = "HC3")

filter(H2HHC3, HC == "HC1", criterion == "size") %>%
  ggplot(aes(x = naive,
             y = p05,
             color = comp)) +
    geom_point(size = 1) +
    geom_abline(intercept = 0, slope = 1) + 
    geom_hline(aes(yintercept = .05)) + 
    geom_vline(aes(xintercept = .05)) +
    geom_hline(aes(yintercept = .05427), linetype = "dashed")+
    geom_vline(aes(xintercept = .05427), linetype = "dashed") +
    facet_wrap(~test) +
  labs(title = "HC1 vs Naive HC2",
       y = "HC1",
       x = "HC3")



```

```{r, cache = T, echo = F, warning = F, results = "asis", fig.width = 15, fig.height = 15}
HC3 <- filter(results, HC == "HC3", criterion == "size", test == "naive", n == 25) %>%
  select(n:Edist, coef, naive = p05)

compare <- function(vals, nom = .05427) {
  if(vals[1] > nom & vals[2] <= nom) return("y")
  if(vals[1] <= nom & vals[2] > nom) return("x")
  if(vals[1] > nom & vals[2] > nom & vals[1] > vals[2]) return("y")
  if(vals[1] > nom & vals[2] > nom & vals[1] < vals[2]) return("x")
  if(vals[1] <= nom & vals[2] <= nom & vals[1] > vals[2]) return("x")
  if(vals[1] <= nom & vals[2] <= nom & vals[1] < vals[2]) return("y")
  return("equal")
}


filter(results, criterion == "size", n == 25) %>%
  merge(HC3) %>%
  mutate(comp = unlist(apply(cbind(x = naive, y = p05), 1, compare))) ->
  H2HHC3

group_by(H2HHC3, HC, test) %>%
  summarize(percs = paste(round(mean(comp == "x"),2), round(mean(comp == "y"),2), sep = "\n")) -> 
  perc

ggplot(H2HHC3, aes(x = naive,
             y = p05,
             color = comp)) +
    geom_point(size = 1) +
    geom_abline(intercept = 0, slope = 1) + 
    geom_hline(aes(yintercept = .05)) + 
    geom_vline(aes(xintercept = .05)) +
    geom_hline(aes(yintercept = .05427), linetype = "dashed")+
    geom_vline(aes(xintercept = .05427), linetype = "dashed") +
    facet_grid(HC ~ test) +
  labs(title = "All Models vs Naive HC3 @ n = 25",
       y = "HC1",
       x = "HC3") +
  geom_text(data = perc, 
            aes(x = .07, 
                y = .15, 
                label = percs, 
                size = 5,
                color = NA), 
            parse = F)

```
